### ISSUE TITLE
Proposed Additional PR checklist 

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/OpenPBTA-analysis#106]
## Issue 

I made a PR checklist inspired by the OpenPBTA project guidelines. This has been helpful for me personally, and I therefore believe that it can be helpful to other contributors. It would serve as an additional and optional resource. 

The checklist is in markdown format and can be found below.

### PR checklist

- [ ] [Fork](https://help.github.com/en/articles/fork-a-repo) the repo. 
You only need to do this step once, continue to the third step of this list if you have already done this. 
- [ ] Make the original repo, `AlexsLemonade/OpenPBTA-analysis`, an [upstream repository](https://help.github.com/en/articles/configuring-a-remote-for-a-fork).
- [ ] Checkout a [new branch](https://gist.github.com/markSci5/5916003) to make changes on. 
**WAIT** Is your master branch up to date with the upstream repo?  
Try `git status` to check. 
If it's not, go [here](https://help.github.com/en/articles/syncing-a-fork) before creating your new branch. 
Remember to `git push` when you are done. 
- [ ] Did you make numerous changes, too many for one pull request? 
Then let's create [stacked pull requests](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#creating-stacked-pull-requests). 
- [ ] Now that you have committed changes, be sure to write a detailed summary of the changes by following this [template](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/PULL_REQUEST_TEMPLATE.md).     

Now check to ensure you have done the following before filing the PR (remember to push any additional changes): 

- [ ] Run a linter (using [styler](http://styler.r-lib.org/) for example)
- [ ] Set the seed (if applicable)
- [ ] Structure of analysis directory meets the [Project Structure](https://github.com/AlexsLemonade/OpenPBTA-analysis#folder-structure) guidelines
- [ ] Comments and/or documentation up to date
- [ ] Double checked paths
- [ ] Spell check any Rmd file or md file (using [mdspell](https://github.com/mtuchowski/mdspell) for example)
- [ ] Restart R and run all notebooks fresh and save (be sure to [run in the Docker container](https://github.com/AlexsLemonade/OpenPBTA-analysis#development-in-the-project-docker-container)) 
- [ ] Connect the pertinent issues on ZenHub
- [ ] Updated Dockerfile and built Docker image successfully
- [ ] Added analysis to [continuous integration](https://github.com/AlexsLemonade/OpenPBTA-analysis#adding-analyses-to-ci)

## Question

Is it necessary to add this checklist to the repo?

**Comment by jaclyn-taroni** [comment]
I think we've put a lot of what was captured in the first checklist here into `CONTRIBUTING.md` since this was initially filed. I like the second checklist but I think it would be burdensome in this particular context (not everyone uses R Notebooks, for example). I am going to close this and tag it with `thoughts for v2` if we every think about implementing style guides.
