### ISSUE TITLE
Updates required post v22 histologies file release

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1368]
Per my comments on #1365, some LGG `cancer_group` updates were implemented, but never transferred to `pbta-histologies.tsv`. This resulted in separate `cancer_group` in plots for `Low-grade glioma astrocytoma` (LGGA) and ganglioglioma but not PXA, pilocytic, and SEGA because they remained within LGGA:

```r
# v21 rna
v21 %>%
  filter((short_histology == "LGAT" | short_histology == "Ganglioglioma") & experimental_strategy == "RNA-Seq") %>%
  select(cancer_group, tumor_descriptor) %>%
  table()
                                     tumor_descriptor
cancer_group                          Initial CNS Tumor Progressive Recurrence Second Malignancy
  Ganglioglioma                                      36           8          3                 0
  Low-grade glioma astrocytoma                      200          31         12                 1
  Pilocytic astrocytoma                               0           1          0                 0
  Pleomorphic xanthoastrocytoma                       2           0          0                 0
  Subependymal Giant Cell Astrocytoma                 3           1          0                 0

#v22 rna
histology %>%
  filter((short_histology == "LGAT" | short_histology == "Ganglioglioma") & experimental_strategy == "RNA-Seq") %>%
  select(cancer_group, tumor_descriptor) %>%
  table()
                                     tumor_descriptor
cancer_group                          Initial CNS Tumor Progressive Recurrence Second Malignancy
  Diffuse fibrillary astrocytoma                      5           0          1                 0
  Ganglioglioma                                      36           8          3                 0
  Gliomatosis cerebri                                 1           0          0                 0
  Low-grade glioma astrocytoma                       72          16          6                 0
  Oligodendroglioma                                   1           0          0                 0
  Pilocytic astrocytoma                             106          15          4                 1
  Pleomorphic xanthoastrocytoma                       9           1          1                 0
  Subependymal Giant Cell Astrocytoma                11           1          0                 0

#v21 dna 
v21 %>%
  filter((short_histology == "LGAT" | short_histology == "Ganglioglioma") & experimental_strategy != "RNA-Seq") %>%
  select(cancer_group, tumor_descriptor) %>%
  table()
                                     tumor_descriptor
cancer_group                          Initial CNS Tumor Progressive Recurrence Second Malignancy
  Diffuse fibrillary astrocytoma                      1           0          0                 0
  Ganglioglioma                                      35          10          3                 0
  Low-grade glioma astrocytoma                      190          30         13                 1
  Pilocytic astrocytoma                               1           1          0                 0
  Pleomorphic xanthoastrocytoma                       1           0          0                 0
  Subependymal Giant Cell Astrocytoma                 2           1          0                 0

#v22 dna
histology %>%
  filter((short_histology == "LGAT" | short_histology == "Ganglioglioma") & experimental_strategy != "RNA-Seq") %>%
  select(cancer_group, tumor_descriptor) %>%
  table()
                                     tumor_descriptor
cancer_group                          Initial CNS Tumor Progressive Recurrence Second Malignancy
  Diffuse fibrillary astrocytoma                      5           0          1                 0
  Ganglioglioma                                      35          10          3                 0
  Gliomatosis cerebri                                 1           0          0                 0
  Low-grade glioma astrocytoma                       67          16          6                 0
  Oligodendroglioma                                   1           0          0                 0
  Pilocytic astrocytoma                             101          14          5                 1
  Pleomorphic xanthoastrocytoma                       9           1          1                 0
  Subependymal Giant Cell Astrocytoma                11           1          0                 0
```

Therefore, sadly, we will need to update some modules and figures with the v22 histology file cancer group mappings and it looks like we will need additional colors for `Pilocytic astrocytoma`, `Subependymal Giant Cell Astrocytoma`, and possibly `Pleomorphic xanthoastrocytoma` if we have modules using > Initial CNS Tumor (chromothripsis looks to be one of these).

**Color codes to be generated**
- https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/mapping-histology-labels.Rmd with `Pilocytic astrocytoma` (PAST can be used as the abbreviation, per http://oncotree.mskcc.org/#/home), `Subependymal Giant Cell Astrocytoma` (SEGA), and possibly `Pleomorphic xanthoastrocytoma` (PXA).

**Figures to rerun/replace and modules**
- [x] Figure 1B sample distribution via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig1-sample-distribution.R #1456 
- [x] Figure 2A LGG oncoprint via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig2-oncoprint-landscape.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1519
- [x] Figure 3A-B mutational co-occurrence via https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/interaction-plots #1453 
- [x] Figure 3D chromothripsis barplot via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig3-chromothripsis-barplot.R #1457 
- [x] Figure 3E mutational sig weights via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/mutational-signatures/07-plot_cns_fit.Rmd #1476 
- [x] Figure 4D tp53/telomerase score barplots via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig4-tp53-telomerase-panels.R
- [x] Figure 4F tp53/telomerase forest plot via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig4-tp53-telomerase-panels.R #1480 
- [x] Figure 5B GSVA heatmap via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig5-panels-gsva-umap.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1511
- [x] Figure 5D quantiseq fractions forest plot via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig5-forest-plot.R #1480 
- [x] Figure 5C, S6E, S6F quantiseq fractions via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/02-visualize_quantiseq.Rmd #1458 
- [x] Figure S2H TMB distribution via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/supp-tmb-compare-panels.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1512
- [x] Figure S3A other cancer group oncoprint via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/fig2-oncoprint-landscape.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1519
- [x] Figure S3B CNV genomic view and S3C-D chromothripsis box/jitter plots via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/supp-S3-panels-BCD.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1457 #1480 
- [x] Figure S4A-B individual mut sigs and sig 1 by tumor descriptor via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/mutational-signatures/07-plot_cns_fit.Rmd #1476 
- [x] Figure S6C LGG umap via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/scripts/supp-subtype-umap.R https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1513

**Tables to replace and modules**
- [x] Table 1 molecular subtypes should be checked via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd - it may not need an update. #1448 
- [x] Table S1 histologies file via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd #1448 
- [x] Table S4 survival fit results via https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd #1448

**Comment by jharenza** [comment]
Noting that the remaining to-dos are in PR now and this can be closed when #1448, #1458, #1515, and #1519 are merged

**Comment by jharenza** [comment]
Closing in favor of #1487 tracking figures now
