### ISSUE TITLE
Planned data release: V12

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#326]
#### What data file(s) does this issue pertain to?
data release v12

#### What release are you using?

NA

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Will add:
- [x] newly sequenced and processed stranded RNA-Seq for 23 PNOC samples and 21 CBTTC samples - will update expression files, fusion files
- [ ] updated clinical file to capture BS_IDs from above samples
- [x] GISTIC results for CNVkit (#244) - comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/244#issuecomment-564280056)
- [ ] recurrently-fused genes list by patient and histology #10 
- [x] updated TMB files #311 #307

@jaclyn-taroni - we will have to re-release consensus rna-seq files and fusion files in a subsequent release. should we do this immediately after v12 or do a "silent" v12 in which we run these analyses, then a public v13 to capture all of the changes?

**Comment by jaclyn-taroni** [comment]
Summarizing a conversation from Slack: The consensus fusion and collapsed RNA-seq files will be included in the v12 release as someone will run the `collapse-rnaseq` module (instructions [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/collapse-rnaseq)) and [`fusion_filtering` module](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) upstream of the release.

**Comment by cansavvy** [comment]
Updated TMB and consensus files are added to S3 (date: 2019-12-12).

**Comment by jharenza** [comment]
> openpbta/snv-consensus

@cansavvy can you send me the direct S3 link? I know it was in an old PR but can't readily find it.

**Comment by cansavvy** [comment]
> > openpbta/snv-consensus
> 
> @cansavvy can you send me the direct S3 link? I know it was in an old PR but can't readily find it.

https://open-pbta.s3.amazonaws.com/data/snv-consensus/snv-consensus-20191212.zip

**Comment by cansavvy** [comment]
I see a bit of conversation occurred about the consensus file names while I was gone: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/293 Would you like me to change the file names on S3 to fit the new convention?

**Comment by jharenza** [comment]
@cansavvy, nah, we can rename since that file is also being hosted on the same bucket as the other v12 data

**Comment by jaclyn-taroni** [comment]
Closed via #347
