### ISSUE TITLE
Data release documentation checklist

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#343]
We now have (#336) or are proposing (#342) multiple files that contain information about data files in addition to the release notes that are typically associated with a data release. I am proposing the following check list that should accompany data release pull requests to make it easier to get all of our ducks in a row for each data release

- [ ] Is the table in `doc/data-description.md` up to date?
- [ ] Is `doc/data-format.md` up to date?
- [ ] Is `doc/release-notes.md` up to date?

**Comment by jharenza** [comment]
submitted PR #348 for this

**Comment by jaclyn-taroni** [comment]
Closed via #350
