### ISSUE TITLE
Planned data release: V13

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#373]
#### What data file(s) does this issue pertain to?
For V13, on deck:
- [x] Update RNA-Seq stranded files, per #369, #371, #370  
- [x] Add bed files per #351 
- [x] Add MendQC data files per #341 
- [x] Add Consensus CNVs per #128 
- [x] remove BGI-China data per #374 (comment below)
- [x] potentially include fusion files from #398 
- [x] address #379 

#### What release are you using?
V12

#### Put your question or report your issue here.
Any additional files to add?

**Comment by jaclyn-taroni** [comment]
@jharenza can we plan to remove the poly-A stranded samples that were added as part of v12? Related to @jashapiro's results here: #374 I think including them is likely to confuse folks working with the data.

**Comment by jharenza** [comment]
yes, was going to ask if we should do so

**Comment by jharenza** [comment]
We will also be adding merged MAFs and a clinical file for #257 with this release.

**Comment by jaclyn-taroni** [comment]
Closed via #444
