### ISSUE TITLE
Planned release: v15

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#543]
#### What data file(s) does this issue pertain to?
Updated fusion files, TCGA MAFs, clinical file

#### What release are you using?

v14

#### Put your question or report your issue here.
Fusion files need to be updated because of updated kinase reference list and old v13 recurrently-fused-genes files in v14

- [x] pbta-fusion-recurrently-fused-genes-byhistology.tsv per [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/539#issuecomment-587167746) and #553
- [x] pbta-fusion-putative-oncogenic.tsv per #530 , #553 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/521#issuecomment-582990375)
- [x] pbta-fusion-recurrently-fused-genes-bysample.tsv per [comment] (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/539#issuecomment-587167746) and #553
- [x] TCGA MAFs per #257 using BED file from WXS kit
- [x] pbta-histologies.tsv per #541 <s>and possibly add EPN subtypes from #490</s>

**Comment by jharenza** [comment]
@jaclyn-taroni should there be any updates to GISTIC/CN files in V15? We are probably looking at another week or so until we can do a release.

**Comment by cansavvy** [comment]
@jharenza , when you say ` BED file from WXS kit` does that mean using the WXS file: `WXS.hg38.100bp_padded.bed` from the data release?

**Comment by jaclyn-taroni** [comment]
@jharenza re: GISTIC/CN files - I would recommend that we use the consensus GISTIC file in `master` for consistency's sake: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/46cf6ccb119312ccae6122ac94c51710df01f6da/analyses/run-gistic/results/pbta-cnv-consensus-gistic.zip

We can also think about distributing the consensus files here: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/46cf6ccb119312ccae6122ac94c51710df01f6da/analyses/focal-cn-file-preparation/results

**Comment by jharenza** [comment]
@cansavvy no, the BED file from your comment here: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/521#issuecomment-583053607

(sorry, I updated the comment from @kgaonkar6 to be inclusive for v15)

**Comment by jharenza** [comment]
@adamcresnick suggests we change `disease_type_old` and `disease_type_new` to not sound so much like right/wrong/QC, but to reflect all information: `pathology_diagnosis`  and `integrated_diagnosis`, so will update with v15

**Comment by jharenza** [comment]
@yuankunzhu fyi for next release

**Comment by jharenza** [comment]
@jaclyn-taroni - For:

> We can also think about distributing the consensus files here: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/46cf6ccb119312ccae6122ac94c51710df01f6da/analyses/focal-cn-file-preparation/results

You are talking about these two files, correct?
`
consensus_seg_annotated_cn_autosomes.tsv.gz
consensus_seg_annotated_cn_x_and_y.tsv.gz
`

**Comment by jaclyn-taroni** [comment]
Yes @jharenza, that's correct.

**Comment by jharenza** [comment]
Looping in @yuankunzhu and @tkoganti to this thread.

**Comment by jharenza** [comment]
@jashapiro @jaclyn-taroni do we still want `pbta-cnv-cnvkit-gistic.zip` in the data release since we have consensus? right now, that one was processed on d3b's end, so it points to the bash code in our repo, but since we are replacing `pbta-cnv-consensus-gistic.zip` with the GISTIC in docker here, would you also want to update the cnvkit gistic results if we keep them?

**Comment by jharenza** [comment]
closed via #569
