### ISSUE TITLE
Make mapping histology groups for plotting -- Part 2 implementing the use of the mapping table

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#898]
#### Background:

https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/627#issuecomment-754813774: 

- This mapping TSV file (created in #897) needs to be used in all relevant plotting modules (or wherever else smaller "high-level" labels are needed. 

- `histology_color_palette.tsv` will need to be retired after all modules are updated. 

#### Known relevant modules that need this update

- [x] chromosomal-instability/02a-plot-chr-instability-heatmaps.Rmd - Updated in #904
- [x] cnv-chrom-plot/cn-status_heatmap.Rmd - Updated in #911
- [x] mutational-signatures/01-known_signatures.Rmd - Updated in #911
- [x] oncoprint-landscape/01-plot-oncoprint.R - Updated in #918
- [x] sample-distribution-analysis/02-multilayer-plots.R - Updated in #918

** We also need to make sure that the figures/scripts equivalents of these figures are up to date: 

- [x] fig1-sample-distribution.R - Updated in #918
- [ ] TelomeraseActivitites.R
- [ ] transcriptomic-overview.R - Updated in #921 

#### What input data are required for this analysis?

`pbta-histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
This is dependent on #897

**Comment by jaclyn-taroni** [comment]
As we're going through these, let's be careful to make sure that things don't stay commented out in CI. I believe everything covered in #882, where the CI errors are documented, is covered here now and we are going to retire `histology_color_palette.tsv`.

**Comment by jaclyn-taroni** [comment]
As far as I can tell, this is done.
